FROM atendai/evolution-api:v2.0.10

ENV SERVER_URL=https://evolution-api-production.up.railway.app
ENV AUTHENTICATION_API_KEY=8830acf9704e6a493bde3f2fa728bb0ba952fd4c940047ccabb1c2772361ca4f
ENV AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
ENV DATABASE_ENABLED=true
ENV DATABASE_PROVIDER=postgresql
ENV DATABASE_SAVE_DATA_INSTANCE=true
ENV DATABASE_SAVE_DATA_NEW_MESSAGE=true
ENV DATABASE_SAVE_MESSAGE_UPDATE=true
ENV DATABASE_SAVE_DATA_CONTACTS=true
ENV DATABASE_SAVE_DATA_CHATS=true
ENV DATABASE_SAVE_DATA_LABELS=true
ENV DATABASE_SAVE_DATA_HISTORIC=true
ENV RABBITMQ_ENABLED=false
ENV WEBSOCKET_ENABLED=true
ENV WEBSOCKET_GLOBAL_EVENTS=false
ENV WA_BUSINESS_TOKEN_WEBHOOK=evolution
ENV CONFIG_SESSION_PHONE_CLIENT=Evolution API
ENV CONFIG_SESSION_PHONE_NAME=Chrome
ENV QRCODE_LIMIT=30
ENV QRCODE_COLOR=#000000
ENV DEL_INSTANCE=false
ENV CHATWOOT_ENABLED=false
ENV OPENAI_ENABLED=false
ENV DIFY_ENABLED=false
ENV TYPEBOT_ENABLED=false
ENV S3_ENABLED=false
ENV CACHE_REDIS_ENABLED=false
ENV CACHE_LOCAL_ENABLED=true
ENV LOG_LEVEL=WARN
ENV LOG_COLOR=true
ENV LOG_BAILEYS=error

EXPOSE 8080
